# Generated by Django 4.2.4 on 2023-09-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("departments", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="department",
            name="hod_id",
        ),
        migrations.AlterField(
            model_name="department",
            name="description",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
