# Generated by Django 4.2.4 on 2023-09-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("departments", "0003_department_hod_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
