# Generated by Django 4.2.4 on 2023-09-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employees",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                ("dob", models.DateField()),
                (
                    "email",
                    models.CharField(
                        max_length=120, unique=True, verbose_name="Employee's email id"
                    ),
                ),
                ("phone", models.CharField(max_length=15)),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Employee created on date"
                    ),
                ),
                (
                    "updated_on",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Employee updated on date"
                    ),
                ),
            ],
            options={
                "db_table": "employees",
            },
        ),
    ]
