# Generated by Django 4.2.4 on 2023-09-04 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("departments", "0003_department_hod_id"),
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employees",
            name="department_id",
            field=models.ForeignKey(
                db_column="department_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="departments.department",
            ),
        ),
    ]
